[server]
# Network Configuration for RankRight
headless = true
address = "0.0.0.0"
port = 5000

# CORS and Security Settings
enableCORS = false
enableXsrfProtection = false

# Performance Settings
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Disable automatic browser opening
gatherUsageStats = false

[theme]
# Keep default theme unless user requests changes
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"